const express=require('express');
const mongoose=require('mongoose');
const cors=require('cors');
require('dotenv').config();
const app=express();
app.use(cors());
app.use(express.json());
mongoose.connect(process.env.MONGO_URI).then(()=>console.log('MongoDB Connected'));
app.use('/api/transactions',require('./routes/transactionRoutes'));
app.listen(process.env.PORT||5000,()=>console.log('Server Running'));